<head>
    <link rel="stylesheet" href="../styles/general.css">
    <link rel="stylesheet" href="../styles/cabecera.css">
</head>
<header>
    <section id="logo">
        <img src="../imagenes/logo.png">
        <div>Dev Cave</div>
    </section>
    <section class="menu">
        <nav>
            <ul>
                <li><a href="../index.php">Inicio</a></li>
                <li><a href="../paginas/listaJuegos.php">Lista de juegos</a></li>
                <li><a href="../paginas/formulario_juegos.php">Publicar juego</a></li>
            </ul>
        </nav>
    </section>
    <section class="login">
        <a href="../paginas/login.php">Iniciar sesión</a>
    </section>
    <section id="side-menu-button">
        <button><i class="fa fa-bars"></i></button>
    </section>
</header>
<body>
    
</body>
<aside id="aside-menu" class="not-visible">
    <section class="menu">
        <nav>
            <ul>
                <li><a href="../index.php">Inicio</a></li>
                <li><a href="../paginas/listaJuegos.php">Lista de juegos</a></li>
                <li><a href="../paginas/formulario_juegos.php">Publicar juego</a></li>
            </ul>
        </nav>
    </section>
    <section class="login">
        <a href="../paginas/login.php">Iniciar sesión</a>
    </section>
</aside>
<script src="../js/side-button.js">
</script>